version: '3.5'

services:
  gunicorn:
    build: .
    depends_on:
      - huanik
    expose:
      - "5000"
    environment:
      VIRTUAL_HOST: "xn--lhrz38b.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 5000
  huanik:
    image: i3thuan5/hokbu-le:taihua
